#!/usr/bin/env python3
"""Regenerate src/icon-names.ts from the LOCAL Obsidian app's bundled Lucide
dictionary (obsidian.asar), so the icon picker can offer every name the
running app actually resolves via setIcon.

Usage: python3 scripts/extract-icon-names.py [path/to/obsidian.asar]

The dictionary is minified JS mapping icon names (single words unquoted,
hyphenated names quoted) to path-data arrays; both path (`[[6,"..."]`) and
circle (`[[1,12,12,10]`) first nodes must match.
"""
import re
import sys
from pathlib import Path

DEFAULT_ASAR = '/Applications/Obsidian.app/Contents/resources/obsidian.asar'
OUT = Path(__file__).resolve().parent.parent / 'src' / 'icon-names.ts'

def main() -> None:
    asar_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ASAR
    data = Path(asar_path).read_bytes().decode('utf-8', 'ignore')
    names = sorted(set(re.findall(r'[,{]"?([a-z][a-z0-9]*(?:-[a-z0-9]+)*)"?:\[\[(?:\d|6,")', data)))
    if len(names) < 1000:
        raise SystemExit(f'suspiciously few names ({len(names)}) — asar layout changed?')
    OUT.write_text(
        '/** GENERATED by scripts/extract-icon-names.py from Obsidian\'s bundled\n'
        ' *  Lucide dictionary — every icon name the current app resolves through\n'
        ' *  setIcon. Do not hand-edit; regenerate instead. Stored as one raw string\n'
        ' *  (newline-separated, sorted) to keep the data compact.\n'
        ' */\n'
        'const RAW_ICON_NAMES = `\n' + '\n'.join(names) + '`;\n\n'
        'export const BUNDLED_ICON_NAMES: readonly string[] = RAW_ICON_NAMES.trim().split(\'\\n\');\n',
        encoding='utf-8',
    )
    print(f'{OUT}: {len(names)} icon names written')

if __name__ == '__main__':
    main()
